### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by vrgz2022** [stablecabal/gyre#3]
F:\gyre-installer-1.0.0>install_or_update.cmd
已复制         1 个文件。
Using local micromamba
Environment exists. Updating.

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Transaction

  Prefix: F:\gyre-installer-1.0.0\env\envs\gyre

  All requested packages already installed

Transaction starting
Transaction finished

critical libmamba ڶֽڵĿҳУûд Unicode ַӳ䵽ַ

i get this error
and server can't run
cmd windows Close immediately after opening, and see a small line of libmamba error

**Comment by hafriedlander** [comment]
Hello.

Unfortunately micromamba has a problem with Windows with non-english languages.

As a workaround you can:
  - Install miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe
  - Run an "Anaconda Prompt (miniconda3)" from your start menu
  - Run install_or_update.cmd from the shell that opens up.
  
  This should use the miniconda you installed rather than the packaged micromamba.

**Comment by hafriedlander** [comment]
Hi. Closing this as I believe the above should work. Feel free to re-open if still an issue.
